<?php

/**
 * CheckoutCrypto OTP Module - autopay/withdraw/sendfunds/authentication_change One-time passwords
 * Copyright 2014 CheckoutCrypto
 */

error_reporting(~0); ini_set('display_errors', 1);

function ccOTP_menu() {
 	module_load_include('inc', 'ccOTP', 'includes/settings');
	return otp_menu();
}

function ccOTP_generate_form($form, &$form_state) {
	module_load_include('inc', 'ccOTP', 'includes/forms');
	return otp_gen_form();
}

function ccOTP_validate_form($form, &$form_state) {
 	module_load_include('inc', 'ccOTP', 'includes/forms');
	return otp_validate_form($form, $form_state);
}

function ccOTP_form_user_profile_form_alter(&$form,$form_state){
	$finalForm = array();
    	module_load_include('inc','ccOTP','includes/forms');
	array_push($finalForm, otp_profile_mod($form));
	return $finalForm;
}

function otp_gauth_form($form,&$form_state){
    	module_load_include('inc', 'ccOTP', 'includes/forms');
		return otp_gauth();
}

function ccOTP_theme() {
	module_load_include('inc', 'ccOTP', 'includes/settings');
	return otp_theme();
}




function otp_gauth_callback($ajax) {

	if ($ajax) {
		module_load_include('inc', 'ccOTP', 'includes/forms');
	    ctools_add_js('ajax-responder');
	    ctools_include('ajax');
	    ctools_include('modal');
 
		$form_state = array(
		  'ajax' => TRUE,
		  'title' => t('Google Two-factor Authentication Setup'),
		);

		$output = ctools_modal_form_wrapper('otp_gauth', $form_state);

		print ajax_render($output);
		drupal_exit();
	} else {
		return drupal_get_form('otp_gauth_form');
	}
}

/**
 * @} End of "defgroup ccOTP".
 */
